### ISSUE TITLE
Shared vs exclusive locks

### ISSUE THREAD

**Issue by bedge** [PawelJ-PL/PyYADL#3]
As this appears to be the most recent python/redis lock library I'm filing this here. (All the other py-redis-lockers seem to have the same deficiency)

I'd like to have the option for a shared lock vs exclusive lock.

ie; 
- Many clients can grab the shared lock.
- Only a single client can grab the exclusive lock. 
- Exclusive lock can only be taken when there are no outstanding shared locks.

Bonus feature:
Exclusive lock acquire() has the option of preventing new shared locks from being granted.
Maybe lock.ex_acquire(prevent_new_shared_locks=True)
This is to allow an exclusive client to get a chance to run when there's a constant flow of shared lock requests.

**Comment by PawelJ-PL** [comment]
I'm going to implement read/write locks. Thank You for Your suggestion regarding prevent_new_shared_locks. It seems to be nice feature.

**Comment by PawelJ-PL** [comment]
I've added read (non exclusive) - write (exclusive) locks in version 1.0.0

**Comment by bedge** [comment]
You made my day! thanks. This is still an issue that I've been dragging around for a while and this is a perfect solution.
